### ISSUE TITLE
bookstore-UploadBooks outputs the Runtime.ImportModuleError.

### ISSUE THREAD

**Issue by yuuu** [enghwa/MultiRegion-Modern-Architecture#7]
Another problem was raised by upgrading the version of node.js in this pull request.

https://github.com/enghwa/ecommerce-shopfront-on-aws/pull/6

bookstore-UploadBooks that is Custom::CustomResource outputs the following error:

```
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'uuid'",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'uuid'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
```

It looks like you are experiencing the issues described on this page.

https://stackoverflow.com/questions/57906632/lambda-code-works-on-node-v8-10-but-not-nodejs-v10-x

I want to fix this code. Could you tell me the repository ?
https://arc309-bookstore-ap-southeast-1.s3-ap-southeast-1.amazonaws.com/functions/UploadBooks.zip

**Comment by enghwa** [comment]
the original repo is here: https://github.com/aws-samples/aws-bookstore-demo-app/blob/master/functions/setup/uploadBooks.js
this workshop took a subset of that bookstore app and added headless wordpress.
